---
# version to install
seafile_install_version:    '4.0.3'

seafile_time_zone:  'Europe/Brussels'

seafile_fastcgi_enabled:    true

#seafile_server_root:        'https://{{ seafile_ip_or_domain }}/seafhttp'
#seafile_service_url:        'https://{{ seafile_ip_or_domain }}'

# webdav settings
seafile_webdav_enabled:     true
seafile_webdav_fastcgi:     true
seafile_webdav_path:        /dav

# seahub settings
seafile_seahub_admin_email:     test@example.com
seafile_seahub_admin_password:  myDarkS3cr3T

# database settings
seafile_backend:            mysql

#mysql configuration
#
seafile_db_user:            'seafile'
mysql_bind_address:         '{{ seafile_db_host }}'
mysql_db:
- name:                     '{{ seafile_db_name.ccnet }}'
  replicate:                no
- name:                     '{{ seafile_db_name.seafile }}'
  replicate:                no
- name:                     '{{ seafile_db_name.seahub }}'
  replicate:                no
mysql_users:
- name:                     '{{ seafile_db_user }}'
  pass:                     '{{ seafile_db_pass }}'
  priv: >
    {{ seafile_db_name.ccnet    ~ ".*:ALL/" ~
       seafile_db_name.seafile  ~ ".*:ALL/" ~
       seafile_db_name.seahub   ~ ".*:ALL"  }}
mysql_root_db_pass: dark
seafile_db_pass: secret

#nginx configuration
#
nginx_max_clients:          128
nginx_http_params:
  - sendfile                 "on"
  - tcp_nopush               "on"
  - tcp_nodelay              "on"
  - keepalive_timeout        65
  - access_log               "/var/log/nginx/access.log"
  - error_log                "/var/log/nginx/error.log"
  - types_hash_max_size      2048

nginx_sites:
  seafile:
  - listen 80
  - server_name {{ seafile_ip_or_domain }}
  #   - rewrite:        ^ https://$http_host$request_uri? permanent
  #  seafile-ssl:
  #   - listen:         443
  #   - server_name:    '{{ seafile_ip_or_domain }}'
  #   - ssl:            "on"
  #   - ssl_certificate_key:    /etc/ssl/private/server.key.pem
  #   - ssl_certificate:        /etc/ssl/private/server.crt.pem
  - location / {
      fastcgi_pass 127.0.0.1:{{ seafile_fastcgi_port }};
      fastcgi_param SCRIPT_FILENAME     $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO           $fastcgi_script_name;
      fastcgi_param SERVER_PROTOCOL     $server_protocol;
      fastcgi_param QUERY_STRING        $query_string;
      fastcgi_param REQUEST_METHOD      $request_method;
      fastcgi_param CONTENT_TYPE        $content_type;
      fastcgi_param CONTENT_LENGTH      $content_length;
      fastcgi_param SERVER_ADDR         $server_addr;
      fastcgi_param SERVER_PORT         $server_port;
      fastcgi_param SERVER_NAME         $server_name;
      access_log    "/var/log/nginx/seahub.access.log";
      error_log     "/var/log/nginx/seahub.error.log";
    }
  #    fastcgi_param HTTPS               on;
  #    fastcgi_param HTTP_SCHEME         https;
  - location /seafhttp {
      rewrite               ^/seafhttp(.*)$ $1 break;
      proxy_pass            "http://127.0.0.1:{{ seafile_httpserver_port }}";
      client_max_body_size  0;
      proxy_connect_timeout  36000s;
      proxy_read_timeout  36000s;
    }
  - location /media {
      root {{ seafile_latest_dir }}/seahub;
    }
  - location {{ seafile_webdav_path }} {
      fastcgi_pass  127.0.0.1:{{ seafile_webdav_port }};
      fastcgi_param SCRIPT_FILENAME     $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO           $fastcgi_script_name;
      fastcgi_param SERVER_PROTOCOL     $server_protocol;
      fastcgi_param QUERY_STRING        $query_string;
      fastcgi_param REQUEST_METHOD      $request_method;
      fastcgi_param CONTENT_TYPE        $content_type;
      fastcgi_param CONTENT_LENGTH      $content_length;
      fastcgi_param SERVER_ADDR         $server_addr;
      fastcgi_param SERVER_PORT         $server_port;
      fastcgi_param SERVER_NAME         $server_name;
      fastcgi_param HTTP_SCHEME         "http";
      client_max_body_size                50m;
      access_log    "/var/log/nginx/seafdav.access.log";
      error_log     "/var/log/nginx/seafdav.error.log";
    }
